### ISSUE TITLE
ls returns "error: ENOENT"

### ISSUE THREAD

**Issue by xtoto1** [Andy-Python-Programmer/aero#11] opened 2021-12-07 11:21 UTC
![image](https://user-images.githubusercontent.com/74153455/145019532-cee48ffd-1350-4596-a675-d1417a8d4655.png)

I don't remember doing anything except rebooting Aero with `ls` previously working correctly to get the error.

**Comment by Andy-Python-Programmer** [comment] 2021-12-08 07:08
Hmm. I am not able to reproduce it in Qemu. Can you please apply the following diff and try to run the command again and paste the image of what the output after applying this diff.

```diff
diff --git a/userland/aero_shell/src/main.rs b/userland/aero_shell/src/main.rs
index 1fdad80cb..80b134b57 100644
--- a/userland/aero_shell/src/main.rs
+++ b/userland/aero_shell/src/main.rs
@@ -149,9 +149,10 @@ fn main() -> Result<(), AeroSyscallError> {
         let mut buffer = [0u8; 256];
         let len = sys_read(0, &mut buffer)?;

-        let mut command_iter = unsafe { core::str::from_utf8_unchecked(&mut buffer) }.trim()
-            [0..len]
-            .split_whitespace();
+        let ins = &unsafe { core::str::from_utf8_unchecked(&mut buffer) }.trim()[0..len];^M
+        let mut command_iter = ins.split_whitespace();^M
+^M
+        println!("{:?}", ins);^M

         let command = command_iter.next();
```

To apply the diff:
* Copy the diff into a file (call it `b.diff`)
* Run `git apply b.diff`

**Comment by xtoto1** [comment] 2021-12-08 08:17
This is the output i get after applying the diff. Every command seems to work after returning all the '\u{0}''s except `ls` which still returns 'error: ENOENT'
![image](https://user-images.githubusercontent.com/74153455/145172676-c3c77bde-5652-4809-b029-b62db645bc91.png)

**Comment by Andy-Python-Programmer** [comment] 2021-12-10 08:06
Hmm. So it looks like the `NUL` characters are occurring after you have pressed enter. Can you try out printing the `StdinBuffer` and `TtyState` on each key press?

```diff
diff --git a/src/aero_kernel/src/drivers/tty.rs b/src/aero_kernel/src/drivers/tty.rs
index b94d0a794..d7ea3db77 100644
--- a/src/aero_kernel/src/drivers/tty.rs
+++ b/src/aero_kernel/src/drivers/tty.rs
@@ -358,7 +358,25 @@ impl KeyboardListener for Tty {
             }

             _ => {}
-        }
+        };
+
+        let stdin = self.stdin.lock_irq();
+        log::debug!(
+            "lshift={}, rshift={}, lctrl={}, rctrl={}, lalt={}, altgr={}, caps={}",
+            state.lshift,
+            state.rshift,
+            state.lctrl,
+            state.rctrl,
+            state.lalt,
+            state.altgr,
+            state.caps,
+        );
+        log::debug!(
+            "back_buffer={:?}, front_buffer={:?}, cursor={:?}",
+            stdin.back_buffer,
+            stdin.front_buffer,
+            stdin.cursor
+        );
     }
 }
```

**Comment by xtoto1** [comment] 2021-12-10 08:33
After applying the diff there doesnt seem to be much of a difference other than the key presses being printed on the host terminal: 
![image](https://user-images.githubusercontent.com/74153455/145542406-fcee75ed-7b8f-4ce0-8975-8dbcf8d5ae32.png)

but after entering an actual command(ls in this example) i just get this again:
![image](https://user-images.githubusercontent.com/74153455/145542614-2e93db4a-4149-4ee2-8b12-4b3064805a34.png)

i am not using any special flags

**Comment by Andy-Python-Programmer** [comment] 2021-12-10 08:35
Yep can you paste the serial logs in the host terminal here. The prints here are used to debug the actual problem not solve it.

**Comment by xtoto1** [comment] 2021-12-10 14:18
i piped `cargo aero run` into `log.txt` and this is the output:
[log.txt](https://github.com/Andy-Python-Programmer/aero/files/7693286/log.txt)

i used the commands `clear` and `ls` in order, then shut down

**Comment by Andy-Python-Programmer** [comment] 2021-12-11 07:35
That helped to debug and reproduce the issue! Now it should be fixed :^)

**Closed** 2021-12-11 07:35 UTC
